import React, { useState } from 'react';
import { 
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, ReferenceLine,
  ScatterChart, Scatter, Legend 
} from 'recharts';

// --- STATIC DATA: CLUSTER PROFILES ---
const CLUSTER_PROFILES = [
  {
    id: 0,
    color: "#e3f2fd", // Light Blue
    borderColor: "#2196f3",
    title: "Cluster 0: The Engaged (Cross-Sell)",
    description: "High-value customers who have responded positively to previous campaigns or have been contacted recently.",
    traits: ["High previous success rate", "Recently contacted", "High engagement duration"],
    strategy: "Cross-Sell Premium Packages & Upsells"
  },
  {
    id: 1,
    color: "#fff3e0", // Light Orange
    borderColor: "#ff9800",
    title: "Cluster 1: The Savers (Retention)",
    description: "Conservative customers, often contacted during stable economic periods. They prefer security over risk.",
    traits: ["Stable employment rates", "Sensitive to interest rates", "Conservative profile"],
    strategy: "Promote Fixed Deposits & Long-term Savings"
  },
  {
    id: 2,
    color: "#e8f5e9", // Light Green
    borderColor: "#4caf50",
    title: "Cluster 2: New Prospects (Acquisition)",
    description: "The general mass market with no prior contact history. These are standard cold leads.",
    traits: ["No previous contact (999 pdays)", "High competition periods", "Standard demographics"],
    strategy: "Low-barrier Introductory Offers"
  }
];

function App() {
  const [view, setView] = useState('predict'); // 'predict' or 'train'

  return (
    <div style={{ fontFamily: '"Segoe UI", Roboto, Helvetica, Arial, sans-serif', maxWidth: '1300px', margin: '0 auto', color: '#333' }}>
      
      {/* HEADER & NAV */}
      <div style={{ padding: '20px 20px 0 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #eee', marginBottom: '30px' }}>
        <div>
          <h1 style={{ color: '#2c3e50', margin: '0 0 5px 0', fontSize: '1.8em' }}>🏦 Intelligent Bank Campaign</h1>
          <p style={{ color: '#7f8c8d', margin: 0, fontSize: '0.9em' }}>AI-Powered Customer Segmentation</p>
        </div>
        
        <div style={{ display: 'flex', gap: '10px' }}>
          <button 
            onClick={() => setView('predict')}
            style={{ 
              padding: '10px 20px', 
              border: 'none', 
              borderRadius: '6px', 
              background: view === 'predict' ? '#2c3e50' : 'transparent',
              color: view === 'predict' ? '#fff' : '#2c3e50',
              cursor: 'pointer',
              fontWeight: 'bold'
            }}
          >
            Predict Strategy
          </button>
          <button 
            onClick={() => setView('train')}
            style={{ 
              padding: '10px 20px', 
              border: 'none', 
              borderRadius: '6px', 
              background: view === 'train' ? '#2c3e50' : 'transparent',
              color: view === 'train' ? '#fff' : '#2c3e50',
              cursor: 'pointer',
              fontWeight: 'bold'
            }}
          >
            Retrain Model
          </button>
        </div>
      </div>
      
      {/* FIX: Instead of conditional rendering (which unmounts components), 
         we render BOTH but hide one with CSS. This preserves state. 
      */}
      <div style={{ padding: '0 20px 20px 20px' }}>
        <div style={{ display: view === 'predict' ? 'block' : 'none' }}>
          <PredictionView />
        </div>
        <div style={{ display: view === 'train' ? 'block' : 'none' }}>
          <TrainingView />
        </div>
      </div>
      
      {/* PROFILES FOOTER */}
      <div style={{ marginTop: '60px', padding: '0 20px 40px 20px' }}>
        <h3 style={{ borderBottom: '2px solid #eee', paddingBottom: '10px', color: '#2c3e50' }}>Cluster Reference Guide</h3>
        <p style={{ color: '#666', marginBottom: '20px' }}>Understanding the customer segments generated by the K-Prototypes model.</p>
        
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '20px' }}>
          {CLUSTER_PROFILES.map((profile) => (
            <div key={profile.id} style={{ 
              backgroundColor: profile.color, 
              border: `1px solid ${profile.borderColor}`,
              borderRadius: '8px', 
              padding: '20px'
            }}>
              <h4 style={{ margin: '0 0 10px 0', color: '#333' }}>{profile.title}</h4>
              <p style={{ fontSize: '0.9em', lineHeight: '1.5', color: '#555', marginBottom: '15px' }}>{profile.description}</p>
              
              <div style={{ fontSize: '0.85em', fontWeight: 'bold', color: '#444', marginBottom: '5px' }}>Defining Traits:</div>
              <ul style={{ margin: 0, paddingLeft: '20px', fontSize: '0.85em', color: '#666' }}>
                {profile.traits.map((trait, i) => (
                  <li key={i}>{trait}</li>
                ))}
              </ul>
              
              <div style={{ marginTop: '15px', paddingTop: '10px', borderTop: '1px solid rgba(0,0,0,0.1)', fontSize: '0.9em' }}>
                <strong>Best Strategy:</strong> {profile.strategy}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// --- SUB-COMPONENT: PREDICTION VIEW ---
function PredictionView() {
  const [formData, setFormData] = useState({
    age: 30,
    job: 'admin.',
    marital: 'single',
    education: 'university.degree',
    default: 'no',
    housing: 'yes',
    loan: 'no',
    contact: 'cellular',
    month: 'may',
    day_of_week: 'mon',
    campaign: 1,
    pdays: 999,
    previous: 0,
    poutcome: 'nonexistent',
    emp_var_rate: 1.1,
    cons_price_idx: 93.994,
    cons_conf_idx: -36.4,
    euribor3m: 4.857,
    nr_employed: 5191.0
  });

  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleChange = (e) => {
    const { name, value } = e.target;
    const numericFields = ['age', 'campaign', 'pdays', 'previous', 'emp_var_rate', 'cons_price_idx', 'cons_conf_idx', 'euribor3m', 'nr_employed'];
    const finalValue = numericFields.includes(name) ? parseFloat(value) : value;
    setFormData({ ...formData, [name]: finalValue });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      const response = await fetch('http://127.0.0.1:8000/predict_campaign', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });
      if (!response.ok) throw new Error('Network response was not ok');
      const data = await response.json();
      setResult(data);
    } catch (err) {
      setError('Failed to connect to the server.');
    } finally {
      setLoading(false);
    }
  };

  const getClusterPoints = (points, clusterId) => {
    if(!points) return [];
    return points.filter(p => p.cluster === clusterId);
  };

  return (
    <div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))', gap: '30px', marginBottom: '50px' }}>
        {/* FORM COLUMN */}
        <div style={{ backgroundColor: '#fff', padding: '25px', borderRadius: '12px', boxShadow: '0 4px 6px rgba(0,0,0,0.1)', borderTop: '5px solid #2c3e50' }}>
          <h3 style={{ marginTop: 0, borderBottom: '2px solid #f0f0f0', paddingBottom: '10px' }}>Customer Details</h3>
          <form onSubmit={handleSubmit} style={{ display: 'grid', gap: '15px' }}>
             {/* ROW 1: Age & Job */}
             <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
              <div>
                <label style={{ display: 'block', fontSize: '0.9em', marginBottom: '5px', fontWeight: 'bold' }}>Age</label>
                <input type="number" name="age" value={formData.age} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: '0.9em', marginBottom: '5px', fontWeight: 'bold' }}>Job</label>
                <select name="job" value={formData.job} onChange={handleChange} style={inputStyle}>
                  <option value="admin.">Admin</option>
                  <option value="blue-collar">Blue-collar</option>
                  <option value="technician">Technician</option>
                  <option value="services">Services</option>
                  <option value="management">Management</option>
                  <option value="retired">Retired</option>
                  <option value="student">Student</option>
                  <option value="housemaid">Housemaid</option>
                  <option value="unemployed">Unemployed</option>
                  <option value="entrepreneur">Entrepreneur</option>
                </select>
              </div>
            </div>

            {/* ROW 2: Campaign & Day of Week */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
                <div>
                    <label style={{ display: 'block', fontSize: '0.9em', marginBottom: '5px', fontWeight: 'bold', color: '#0277bd' }}>Campaign Contacts </label>
                    <input type="number" name="campaign" min="1" max="50" value={formData.campaign} onChange={handleChange} style={{...inputStyle, borderColor: '#0277bd'}} />
                    <small style={{fontSize: '0.75em', color: '#666', display: 'block', marginTop: '4px'}}>Number of contacts performed</small>
                </div>
                <div>
                    <label style={{ display: 'block', fontSize: '0.9em', marginBottom: '5px', fontWeight: 'bold', color: '#0277bd' }}>Day of Week</label>
                    <select name="day_of_week" value={formData.day_of_week} onChange={handleChange} style={{...inputStyle, borderColor: '#0277bd'}}>
                        <option value="mon">Monday</option>
                        <option value="tue">Tuesday</option>
                        <option value="wed">Wednesday</option>
                        <option value="thu">Thursday</option>
                        <option value="fri">Friday</option>
                    </select>
                </div>
            </div>

            {/* ROW 3: Marital & Education */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
              <div>
                 <label style={{ display: 'block', fontSize: '0.9em', marginBottom: '5px', fontWeight: 'bold' }}>Marital Status</label>
                 <select name="marital" value={formData.marital} onChange={handleChange} style={inputStyle}>
                  <option value="married">Married</option>
                  <option value="single">Single</option>
                  <option value="divorced">Divorced</option>
                 </select>
              </div>
              <div>
                <label style={{ display: 'block', fontSize: '0.9em', marginBottom: '5px', fontWeight: 'bold' }}>Education</label>
                <select name="education" value={formData.education} onChange={handleChange} style={inputStyle}>
                  <option value="university.degree">University Degree</option>
                  <option value="high.school">High School</option>
                  <option value="basic.9y">Basic 9y</option>
                  <option value="professional.course">Professional Course</option>
                  <option value="basic.4y">Basic 4y</option>
                  <option value="basic.6y">Basic 6y</option>
                </select>
              </div>
            </div>

            {/* ROW 4: Financials */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '10px' }}>
               <div>
                <label style={{ display: 'block', fontSize: '0.8em', marginBottom: '5px' }}>Housing Loan</label>
                <select name="housing" value={formData.housing} onChange={handleChange} style={inputStyle}>
                  <option value="yes">Yes</option>
                  <option value="no">No</option>
                </select>
               </div>
               <div>
                <label style={{ display: 'block', fontSize: '0.8em', marginBottom: '5px' }}>Personal Loan</label>
                <select name="loan" value={formData.loan} onChange={handleChange} style={inputStyle}>
                  <option value="yes">Yes</option>
                  <option value="no">No</option>
                </select>
               </div>
               <div>
                 <label style={{ display: 'block', fontSize: '0.8em', marginBottom: '5px' }}>Has Unpaid Debt?</label>
                 <select name="default" value={formData.default} onChange={handleChange} style={inputStyle}>
                  <option value="no">No</option>
                  <option value="unknown">Unknown</option>
                  <option value="yes">Yes</option>
                 </select>
               </div>
            </div>

            {/* ROW 5: History & Economics */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
                <div>
                   <label style={{ display: 'block', fontSize: '0.9em', marginBottom: '5px', fontWeight: 'bold' }}>Previous Contact Outcome</label>
                   <select name="poutcome" value={formData.poutcome} onChange={handleChange} style={inputStyle}>
                     <option value="nonexistent">Nonexistent (Cold Lead)</option>
                     <option value="failure">Failure (Rejected Before)</option>
                     <option value="success">Success (Accepted Before)</option>
                   </select>
                </div>
                <div>
                   <label style={{ display: 'block', fontSize: '0.9em', marginBottom: '5px', fontWeight: 'bold' }}>Euribor 3 Months</label>
                   <input type="number" step="0.001" name="euribor3m" value={formData.euribor3m} onChange={handleChange} style={inputStyle} />
                </div>
            </div>

            <button type="submit" disabled={loading} style={{ marginTop: '10px', padding: '12px', backgroundColor: loading ? '#95a5a6' : '#2c3e50', color: 'white', border: 'none', borderRadius: '6px', fontSize: '1em', cursor: loading ? 'not-allowed' : 'pointer', transition: 'background 0.3s', width: '100%' }}>
              {loading ? 'Analyzing Profile...' : 'Get Recommendation'}
            </button>
            
            {/* VIZ CHART */}
            {result && result.visualization && (
              <div style={{ marginTop: '20px', borderTop: '1px solid #eee', paddingTop: '15px' }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#333', textAlign: 'center' }}>Cluster Map Visualization</h4>
                <div style={{ width: '100%', height: 300 }}>
                  <ResponsiveContainer>
                    <ScatterChart margin={{ top: 20, right: 20, bottom: 20, left: 20 }}>
                      <XAxis type="number" dataKey="x" name="PC1" hide />
                      <YAxis type="number" dataKey="y" name="PC2" hide />
                      <Tooltip cursor={{ strokeDasharray: '3 3' }} />
                      <Legend verticalAlign="bottom" height={36}/>
                      <Scatter name="Engaged" data={getClusterPoints(result.visualization.background_points, 0)} fill="#2196f3" shape="circle" opacity={0.3} />
                      <Scatter name="Savers" data={getClusterPoints(result.visualization.background_points, 1)} fill="#ff9800" shape="circle" opacity={0.3} />
                      <Scatter name="Prospects" data={getClusterPoints(result.visualization.background_points, 2)} fill="#4caf50" shape="circle" opacity={0.3} />
                      <Scatter name="YOU" data={[result.visualization.user_point]} fill="#ff0000" shape="star" r={100} />
                    </ScatterChart>
                  </ResponsiveContainer>
                </div>
              </div>
            )}
          </form>
        </div>

        {/* RESULTS COLUMN */}
        <div>
          {error && <div style={{ backgroundColor: '#ffcdd2', color: '#c62828', padding: '15px', borderRadius: '8px', marginBottom: '20px' }}>{error}</div>}
          
          {result ? (
            <div style={{ backgroundColor: '#fff', padding: '25px', borderRadius: '12px', boxShadow: '0 4px 15px rgba(0,0,0,0.1)', borderTop: `5px solid ${CLUSTER_PROFILES[result.assigned_cluster]?.borderColor || '#ccc'}` }}>
              <div style={{ textTransform: 'uppercase', fontSize: '0.85em', color: '#7f8c8d', letterSpacing: '1px' }}>AI Analysis Result</div>
              <h2 style={{ color: '#2c3e50', marginTop: '5px' }}>{CLUSTER_PROFILES[result.assigned_cluster]?.title || `Cluster ${result.assigned_cluster}`}</h2>
              
              <div style={{ backgroundColor: '#f8f9fa', padding: '15px', borderRadius: '8px', margin: '20px 0', borderLeft: '4px solid #2c3e50' }}>
                <strong style={{ display: 'block', marginBottom: '5px', color: '#2c3e50' }}>Recommended Strategy:</strong>
                <span style={{ fontSize: '1.2em' }}>{result.recommendation}</span>
              </div>
              
              <div>
                <strong>SHAP Impact Analysis:</strong>
                <div style={{ width: '100%', height: 350, marginTop: '20px' }}>
                    <ResponsiveContainer>
                      <BarChart layout="vertical" data={result.shap_data} margin={{ top: 5, right: 30, left: 40, bottom: 5 }}>
                        <XAxis type="number" hide />
                        <YAxis type="category" dataKey="feature" width={140} style={{ fontSize: '0.75em', fill: '#444' }} />
                        <Tooltip 
                            cursor={{fill: 'transparent'}}
                            content={({ active, payload, label }) => {
                                if (active && payload && payload.length) {
                                const data = payload[0].payload;
                                return (
                                    <div style={{ backgroundColor: '#fff', border: '1px solid #ccc', padding: '10px', boxShadow: '0 2px 4px rgba(0,0,0,0.1)' }}>
                                    <p style={{ fontWeight: 'bold', margin: 0 }}>{label}</p>
                                    <p style={{ margin: 0, color: data.impact > 0 ? '#2196f3' : '#e91e63' }}>
                                        Impact: {data.impact > 0 ? '+' : ''}{data.impact.toFixed(4)}
                                    </p>
                                    <p style={{ margin: 0, fontSize: '0.9em', color: '#666' }}>Actual Value: {data.value}</p>
                                    </div>
                                );
                                }
                                return null;
                            }}
                        />
                        <ReferenceLine x={0} stroke="#333" />
                        <Bar dataKey="impact">
                            {result.shap_data.map((entry, index) => (
                                <Cell key={`cell-${index}`} fill={entry.impact > 0 ? '#2196f3' : '#e91e63'} />
                            ))}
                        </Bar>
                      </BarChart>
                    </ResponsiveContainer>
                </div>
                
                {/* RESTORED SECTION */}
                <div style={{ display: 'flex', justifyContent: 'center', gap: '20px', fontSize: '0.8em', marginTop: '10px' }}>
                    <span style={{ display: 'flex', alignItems: 'center' }}><span style={{ width: 10, height: 10, backgroundColor: '#2196f3', display: 'inline-block', marginRight: 5 }}></span> Positive Impact (Support)</span>
                    <span style={{ display: 'flex', alignItems: 'center' }}><span style={{ width: 10, height: 10, backgroundColor: '#e91e63', display: 'inline-block', marginRight: 5 }}></span> Negative Impact (Oppose)</span>
                </div>

                <div style={{ marginTop: '30px', padding: '15px', backgroundColor: '#f5f5f5', borderRadius: '8px', fontSize: '0.9em', color: '#555', lineHeight: '1.5' }}>
                  <strong>How to read this chart:</strong> This graph visualizes the "SHAP values," which explain the AI's logic. 
                  <ul style={{ margin: '5px 0 0 0', paddingLeft: '20px' }}>
                    <li style={{ marginBottom: '5px' }}><strong>Blue bars (Positive):</strong> Features that push the customer <em>towards</em> this specific cluster profile.</li>
                    <li><strong>Red bars (Negative):</strong> Features that push the customer <em>away</em> from this cluster (or indicate the absence of a trait typical for other clusters).</li>
                  </ul>
                </div>
                <p style={{ fontSize: '0.9em', color: '#999', marginTop: '15px', fontStyle: 'italic' }}>
                  {result.explanation}
                </p>
              </div>
            </div>
          ) : (
             <div style={{ height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8f9fa', borderRadius: '12px', border: '2px dashed #dcdcdc', color: '#adb5bd' }}>
               <div style={{ textAlign: 'center' }}><div style={{ fontSize: '3em', marginBottom: '10px' }}>📊</div>Waiting for input...</div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// --- SUB-COMPONENT: TRAINING VIEW ---
function TrainingView() {
  const [file, setFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState(null);

  const handleFileChange = (e) => {
    setFile(e.target.files[0]);
    setMessage(null);
  };

  const handleTrain = async (e) => {
    e.preventDefault();
    if (!file) {
      setMessage({ type: 'error', text: 'Please select a file first.' });
      return;
    }

    const formData = new FormData();
    formData.append('file', file);

    setLoading(true);
    setMessage(null);

    try {
      const response = await fetch('http://127.0.0.1:8000/train_from_file', {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) throw new Error('Training failed. Check server logs.');

      const data = await response.json();
      setMessage({ type: 'success', text: data.message });
    } catch (err) {
      setMessage({ type: 'error', text: err.message });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', textAlign: 'center' }}>
      <div style={{ backgroundColor: '#fff', padding: '40px', borderRadius: '12px', boxShadow: '0 4px 15px rgba(0,0,0,0.1)' }}>
        <h2 style={{ color: '#2c3e50', marginBottom: '10px' }}>Retrain AI Model</h2>
        <p style={{ color: '#666', marginBottom: '30px' }}>
          Upload a new dataset (CSV or Excel) to update the clustering and recommendation engine. 
          <br/><strong>Note:</strong> This process includes t-SNE visualization mapping and may take 1-2 minutes.
        </p>

        <form onSubmit={handleTrain} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '20px' }}>
          <div style={{ width: '100%', padding: '30px', border: '2px dashed #bdc3c7', borderRadius: '8px', backgroundColor: '#f9f9f9' }}>
            <input 
              type="file" 
              accept=".csv, .xlsx, .xls"
              onChange={handleFileChange}
              style={{ fontSize: '1.1em' }} 
            />
            <div style={{ marginTop: '10px', fontSize: '0.85em', color: '#999' }}>Supported formats: .csv (semicolon or comma), .xlsx</div>
          </div>

          <button 
            type="submit" 
            disabled={loading || !file}
            style={{ 
              padding: '15px 40px', 
              fontSize: '1.1em', 
              backgroundColor: loading ? '#95a5a6' : '#27ae60', 
              color: 'white', 
              border: 'none', 
              borderRadius: '6px',
              cursor: loading ? 'not-allowed' : 'pointer',
              transition: 'all 0.3s'
            }}
          >
            {loading ? 'Training in Progress (Please Wait)...' : 'Start Training'}
          </button>
        </form>

        {message && (
          <div style={{ 
            marginTop: '30px', 
            padding: '15px', 
            borderRadius: '8px', 
            backgroundColor: message.type === 'success' ? '#d4edda' : '#f8d7da',
            color: message.type === 'success' ? '#155724' : '#721c24',
            border: `1px solid ${message.type === 'success' ? '#c3e6cb' : '#f5c6cb'}`
          }}>
            {message.type === 'success' ? '✅ ' : '❌ '} {message.text}
          </div>
        )}
      </div>
    </div>
  );
}

const inputStyle = {
  width: '100%',
  padding: '8px',
  borderRadius: '4px',
  border: '1px solid #ccc',
  backgroundColor: '#fff',
  fontSize: '1em'
};

export default App;